### ISSUE TITLE
 Bag spilling items back into inventory and reseting.

### ISSUE THREAD

**Issue by DoctorZoe** [Tschipp/BuildersBag#8]
Whenever I place items inside the bag's inventory, after I close it, they get put back into my inventory. The bag then resets (losing any module configuration, such as chisel) for one attempt. After I open and close the bag once, the modules I configured earlier come back, but the items are still on my inventory and replacing them on the bag restarts the process.

**Comment by Tschipp** [comment]
I assume you're using the latest version? (1.1.0.9)

**Comment by Tschipp** [comment]
I'm not sure what's going on here. It all works fine on a fresh install. What is your modlist? Does the latest.log say anything special?

**Comment by Tschipp** [comment]
I'm gonna need some more info, otherwise I can't do anything.

**Comment by mailleseraph** [comment]
I was having this same issue, only effects me when playing on a server, playing single player works fine. 

server log snippet:
[15:03:55] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.inventory.Slot.func_111238_b()Z
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NoSuchMethodError: net.minecraft.inventory.Slot.func_111238_b()Z
	at tschipp.buildersbag.common.inventory.ContainerBag.func_75135_a(ContainerBag.java:284) ~[ContainerBag.class:?]
	at tschipp.buildersbag.common.inventory.ContainerBag.func_82846_b(ContainerBag.java:244) ~[ContainerBag.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246) ~[afr.class:?]
	at tschipp.buildersbag.common.inventory.ContainerBag.func_184996_a(ContainerBag.java:426) ~[ContainerBag.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by Tschipp** [comment]
This is very useful, thanks!

**Comment by Tschipp** [comment]
Interestingly, this only happens when blocks are shift-clicked into the bag
